In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time

## Definindo as funções usadas no código

In [ ]:
# Definindo a função bubble sort sem lib (obrigatório)
def bubble_sort(arr):
    lista = np.array(arr)
    n = len(lista)
    for i in range(n):
        for j in range(0, n - i - 1):
            if lista[j] > lista[j + 1]:
                lista[j], lista[j + 1] = lista[j + 1], lista[j]

In [ ]:
def selection_sort(arr):
    lista = np.array(arr.copy())
    n  = len(lista)
    for j in range(n-1):
        min_index = j
        for i in range(j, n):
            if lista[i] < lista[min_index]:
                min_index = i
        lista[j], lista[min_index] = lista[min_index], lista[j]

[64 88 32  1 97 99 67 28 83 34 92 28  8 18 70 81 80 84 65 68]


array([ 1,  8, 18, 28, 28, 32, 34, 64, 65, 67, 68, 70, 80, 81, 83, 84, 88,
       92, 97, 99], dtype=int32)

In [ ]:
def insertion_sort(arr):
    lista = np.array(arr.copy())
    n = len(lista)
    for i in range(n):
        cur = lista[i]
        j = i - 1
        while j >= 0 and lista[j] > cur:
            lista[j+1], lista[j] = lista[j], cur
            j -= 1
    return lista

array([ 4, 15, 20, 24, 44, 44, 47, 56, 61, 64, 65, 68, 75, 79, 82, 89, 91,
       92, 97, 98], dtype=int32)

In [ ]:
def shell_sort(arr):
    lista = np.array(arr.copy())
    n = len(lista)
    gap = n // 2
    while gap >= 1:
        for i in range(n):
            cur = lista[i]
            j = i - gap
            while j >= 0 and lista[j] > cur:
                lista[j+gap], lista[j] = lista[j], cur
                j-= gap
        print(lista)
        gap //= 2

[96 64  4  7 31 71  1 84 26 40 53 39 93 78 42 44 42 16  9 83]
[53 39  4  7 31 44  1 16  9 40 96 64 93 78 42 71 42 84 26 83]
[44  1  4  7 31 53 39 16  9 40 71 42 84 26 42 96 64 93 78 83]
[ 4  1  9  7 31 16 39 26 42 40 44 42 64 53 71 83 78 93 84 96]
[ 1  4  7  9 16 26 31 39 40 42 42 44 53 64 71 78 83 84 93 96]


array([ 1,  4,  7,  9, 16, 26, 31, 39, 40, 42, 42, 44, 53, 64, 71, 78, 83,
       84, 93, 96], dtype=int32)

In [ ]:
def quick_sort(arr):
    lista = arr.copy()
    n = len(lista)
    if len(lista) <= 1:
        return np.array(lista)
    else:
        pivo = lista[n // 2]
        menores = [x for x in lista if x < pivo]
        iguais = [x for x in lista if x == pivo]
        maiores = [x for x in lista if x > pivo]
        return np.hstack([quick_sort(menores), iguais, quick_sort(maiores)]).astype(np.int32)

array([  9,  16,  27,  30,  50,  51,  52,  58,  63,  63,  63,  66,  67,
        72,  80,  86,  94,  99, 100, 100], dtype=int32)

In [60]:
arr = np.random.randint(1,101,20)
def merge_sort(arr, inicio=0, fim=None):
    lista = arr
    if fim is None:
        fim = len(lista)
    if (fim - inicio) > 1:
        meio = (inicio + fim) // 2
        merge_sort(arr, inicio, meio)
        merge_sort(arr, meio, fim)
        merge(lista, inicio, meio, fim)
    return lista

def merge(arr, inicio, meio, fim):
    lista = arr
    esquerda = lista[inicio:meio].copy()
    direita = lista[meio:fim].copy()
    i = 0
    j = 0 
    # i para esquerda j para direita
    for k in range(inicio, fim):
        if i >= len(esquerda):
            lista[k] = direita[j]
            j += 1
        elif j >= len(direita):
            lista[k] = esquerda[i]
            i += 1
        elif esquerda[i] <= direita[j]:
            lista[k] = esquerda[i]
            i += 1
        elif direita[j] < esquerda[i]: #podia ser else, mas quis ilustrar melhor a condição
            lista[k] = direita[j]
            j += 1

merge_sort(arr)

array([ 3, 10, 14, 21, 24, 27, 38, 42, 43, 45, 46, 49, 62, 78, 88, 89, 91,
       93, 95, 96], dtype=int32)

In [43]:
# Definindo a função de retorno do tempo que o array levou a ser ordenado
def tempo_ordenaçao(lista):
    start_time = time.time()
    bubble_sort(lista)
    end_time = time.time()
    total_time = end_time - start_time
    return total_time

## Para o caso dos arrays de size = 1k

In [ ]:
# Gerando os 3 arrays aleatórios de cada caso (1k)
arr1_1k = np.random.randint(1,1001,1000)
arr2_1k = np.random.randint(1,1001,1000)
arr3_1k = np.random.randint(1,1001,1000)
arr_1k_sorted = np.random.randint(1,1001,1000)

# Fazendo um array do pior caso 
arr_wc_1k = np.sort(arr1_1k.copy())[::-1]

array([ 290,  641,  535,   81,  363,  553,  188,  751,    3,  334,  678,
        786,  336,  381,  213,  904,  825,  949,  266,  997,  647,  722,
        100,  156,  507,  449,  620,  280,  575,  540,   65,  726,  649,
        449,   78,  674,  196,  828,  348,  751,  686,  200,  685,  247,
        538,  424,  382,  761,  695,  174,  280,  653,  471,  460,  587,
        923,   36,  657,  709,  917,   39,  999,  565,  867,  392,  910,
        421,  485,  276,  915,  633,  652,  213,  201,  271,  910,  560,
        597,  544,  637,  671,  120,  559,  150,  859,  753,  168,  392,
        646,  948,  646,  103,  536,  433,  438,   57,  184,  395,  398,
        254,  966,  408,  868,  317,  736,  369,   24,  990,  374,  377,
        457,  377,  627,  214,  654,  428,  495,  214,  132,  307,  728,
        631,  685,  552,  873,  321,  989,  685,   48,  432,  657,  837,
        262,  201,  648,   94,   81,  693,   81,  382,  604,  348,  654,
        274,   86,  594,   46,  422,  757,  850,  6

In [101]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_1k =  tempo_ordenaçao(arr1_1k)
print(f"Tempo do primeiro array de 1k: {time_arr1_1k} segundos")
time_arr2_1k = tempo_ordenaçao(arr2_1k)
print(f"Tempo do primeiro array de 1k: {time_arr2_1k} segundos")
time_arr3_1k = tempo_ordenaçao(arr3_1k)
print(f"Tempo do primeiro array de 1k: {time_arr3_1k} segundos")
time_wc_1k = tempo_ordenaçao(arr_wc_1k)
print(f"Tempo do primeiro array de 1k: {time_wc_1k} segundos")

Tempo do primeiro array de 1k: 0.1930835247039795 segundos
Tempo do primeiro array de 1k: 0.18578791618347168 segundos
Tempo do primeiro array de 1k: 0.19089579582214355 segundos
Tempo do primeiro array de 1k: 0.2807576656341553 segundos


In [ ]:
# Fazendo uma média dos 3 casos dos arrays aleatórios
list_arr_1k = np.array([time_arr1_1k, time_arr2_1k, time_arr3_1k])
mean_arr_1k = list_arr_1k.mean()
print(f"Tempo médio de ordenação dos arrays de 1k: {mean_arr_1k} segundos.")


Tempo médio de ordenação dos arrays de 1k 0.18992241223653158 segundos.


## Para o caso dos arrays de size = 5k

In [ ]:
# Gerando os 3 arrays aleatórios de cada caso (5k)
arr1_5k = np.random.randint(1,1001,5000)
arr2_5k = np.random.randint(1,1001,5000)
arr3_5k = np.random.randint(1,1001,5000)
arr_5k_sorted = np.random.randint(1,1001,5000)

arr_wc_5k = np.sort(arr1_5k.copy())[::-1]


In [104]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_5k =  tempo_ordenaçao(arr1_5k)
print(f"Tempo do primeiro array de 5k: {time_arr1_5k} segundos.")
time_arr2_5k = tempo_ordenaçao(arr2_5k)
print(f"Tempo do primeiro array de 5k: {time_arr2_5k} segundos.")
time_arr3_5k = tempo_ordenaçao(arr3_5k)
print(f"Tempo do primeiro array de 5k: {time_arr3_5k} segundos.")
time_wc_5k = tempo_ordenaçao(arr_wc_5k)
print(f"Tempo do primeiro array de 5k: {time_wc_5k} segundos.")

Tempo do primeiro array de 5k: 4.809619188308716 segundos.
Tempo do primeiro array de 5k: 4.79963231086731 segundos.
Tempo do primeiro array de 5k: 4.810579776763916 segundos.
Tempo do primeiro array de 5k: 7.0380988121032715 segundos.


In [ ]:
# Fazendo uma média dos 3 casos dos arrays aleatórios
list_arr_5k = np.array([time_arr1_5k, time_arr2_5k, time_arr3_5k])
mean_arr_5k = list_arr_5k.mean()
print(f"Tempo médio de ordenação dos arrays de 5k {mean_arr_5k} segundos.")

Tempo médio de ordenação dos arrays de 5k: 4.8066104253133135


## Para o caso dos arrays de size = 10k

In [7]:
# Gerando os 3 arrays aleatórios de cada caso (10k)
arr1_10k = np.random.randint(1,1001,10000)
arr2_10k = np.random.randint(1,1001,10000)
arr3_10k = np.random.randint(1,1001,10000)
arr_10k_sorted = np.random.randint(1,1001,10000)

# Fazendo um array do pior caso 
arr_wc_10k = np.sort(arr1_10k.copy())[::-1]

In [107]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_10k =  tempo_ordenaçao(arr1_10k)
print(f"Tempo do primeiro array de 10k: {time_arr1_10k} segundos.")
time_arr2_10k = tempo_ordenaçao(arr2_10k)
print(f"Tempo do primeiro array de 10k: {time_arr2_10k} segundos.")
time_arr3_10k = tempo_ordenaçao(arr3_10k)
print(f"Tempo do primeiro array de 10k: {time_arr3_10k} segundos.")
time_wc_10k = tempo_ordenaçao(arr_wc_10k)
print(f"Tempo do primeiro array de 10k: {time_wc_10k} segundos.")

Tempo do primeiro array de 10k: 20.416730165481567 segundos.
Tempo do primeiro array de 10k: 19.932912588119507 segundos.
Tempo do primeiro array de 10k: 19.279999256134033 segundos.
Tempo do primeiro array de 10k: 28.306299209594727 segundos.


In [142]:
# Fazendo uma média dos 3 casos dos arrays aleatórios
list_arr_10k = np.array([time_arr1_10k, time_arr2_10k, time_arr3_10k])
mean_arr_10k = list_arr_10k.mean()
print(f"Tempo médio de ordenação dos arrays aleatórios de 10k: {mean_arr_10k} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 10k: 19.87654733657837 segundos.


## Para o caso dos arrays de size = 20k

In [ ]:
# Gerando os 3 arrays aleatórios de cada caso (20k)
arr1_20k = np.random.randint(1,1001,20000)
arr2_20k = np.random.randint(1,1001,20000)
arr3_20k = np.random.randint(1,1001,20000)
arr_20k_sorted = np.random.randint(1,1001,20000)

# Fazendo um array do pior caso 
arr_wc_20k = np.sort(arr1_20k.copy())[::-1]

In [123]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_20k =  tempo_ordenaçao(arr1_20k)
print(f"Tempo do primeiro array de 20k: {time_arr1_20k} segundos.")
time_arr2_20k = tempo_ordenaçao(arr2_20k)
print(f"Tempo do primeiro array de 20k: {time_arr2_20k} segundos.")
time_arr3_20k = tempo_ordenaçao(arr3_20k)
print(f"Tempo do primeiro array de 20k: {time_arr3_20k} segundos.")
time_wc_20k = tempo_ordenaçao(arr_wc_20k)
print(f"Tempo do primeiro array de 20k: {time_wc_20k} segundos.")

Tempo do primeiro array de 20k: 78.08658719062805 segundos.
Tempo do primeiro array de 20k: 78.17292809486389 segundos.
Tempo do primeiro array de 20k: 77.88561391830444 segundos.
Tempo do primeiro array de 20k: 114.53103971481323 segundos.


In [141]:
# Fazendo uma média dos 3 casos dos arrays aleatórios
list_arr_20k = np.array([time_arr1_20k, time_arr2_20k, time_arr3_20k])
mean_arr_20k = list_arr_20k.mean()
print(f"Tempo médio de ordenação dos arrays aleatórios de 20k: {mean_arr_20k} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 20k: 78.04837640126546 segundos.


## Para o caso dos arrays de size = 30k

In [ ]:
# Gerando os 3 arrays aleatórios de cada caso (30k)
arr1_30k = np.random.randint(1,1001,30000)
arr2_30k = np.random.randint(1,1001,30000)
arr3_30k = np.random.randint(1,1001,30000)
arr_30k_sorted = np.random.randint(1,1001,30000)

# Fazendo um array do pior caso 
arr_wc_30k = np.sort(arr1_30k.copy())[::-1]

In [130]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_30k =  tempo_ordenaçao(arr1_30k)
print(f"Tempo do primeiro array de 30k: {time_arr1_30k} segundos.")
time_arr2_30k = tempo_ordenaçao(arr2_30k)
print(f"Tempo do primeiro array de 30k: {time_arr2_30k} segundos.")
time_arr3_30k = tempo_ordenaçao(arr3_30k)
print(f"Tempo do primeiro array de 30k: {time_arr3_30k} segundos.")
time_wc_30k = tempo_ordenaçao(arr_wc_30k)
print(f"Tempo do primeiro array de 30k: {time_wc_30k} segundos.")

Tempo do primeiro array de 30k: 181.78800249099731 segundos.
Tempo do primeiro array de 30k: 176.47468042373657 segundos.
Tempo do primeiro array de 30k: 175.87128329277039 segundos.
Tempo do primeiro array de 30k: 258.77386450767517 segundos.


In [131]:
# Fazendo uma média dos 3 casos dos arrays aleatórios
list_arr_30k = np.array([time_arr1_30k, time_arr2_30k, time_arr3_30k])
mean_arr_30k = list_arr_30k.mean()
print(f"Tempo médio de ordenação dos arrays aleatórios de 30k: {mean_arr_30k} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 30k: 178.04465540250143 segundos.


## Para o caso dos arrays de size = 40k

In [ ]:
# Gerando os 3 arrays aleatórios de cada caso (40k)
arr1_40k = np.random.randint(1,1001,40000)
arr2_40k = np.random.randint(1,1001,40000)
arr3_40k = np.random.randint(1,1001,40000)
arr_40k_sorted = np.random.randint(1,1001,40000)

# Fazendo um array do pior caso 
arr_wc_40k = np.sort(arr1_40k.copy())[::-1]

In [133]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_40k =  tempo_ordenaçao(arr1_40k)
print(f"Tempo do primeiro array de 40k: {time_arr1_40k} segundos.")
time_arr2_40k = tempo_ordenaçao(arr2_40k)
print(f"Tempo do primeiro array de 40k: {time_arr2_40k} segundos.")
time_arr3_40k = tempo_ordenaçao(arr3_40k)
print(f"Tempo do primeiro array de 40k: {time_arr3_40k} segundos.")
time_wc_40k = tempo_ordenaçao(arr_wc_40k)
print(f"Tempo do primeiro array de 40k: {time_wc_40k} segundos.")

Tempo do primeiro array de 40k: 320.6755437850952 segundos.
Tempo do primeiro array de 40k: 317.463707447052 segundos.
Tempo do primeiro array de 40k: 317.41262125968933 segundos.
Tempo do primeiro array de 40k: 472.335067987442 segundos.


In [134]:
# Fazendo uma média dos 3 casos dos arrays aleatórios
list_arr_40k = np.array([time_arr1_40k, time_arr2_40k, time_arr3_40k])
mean_arr_40k = list_arr_40k.mean()
print(f"Tempo médio de ordenação dos arrays aleatórios de 40k: {mean_arr_40k} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 40k: 318.5172908306122 segundos.


## Para o caso dos arrays de size = 50k

In [ ]:
# Gerando os 3 arrays aleatórios de cada caso (50k)
arr1_50k = np.random.randint(1,1001,50000)
arr2_50k = np.random.randint(1,1001,50000)
arr3_50k = np.random.randint(1,1001,50000)
arr_50k_sorted = np.random.randint(1,1001,50000)

# Fazendo um array do pior caso 
arr_wc_50k = np.sort(arr1_50k.copy())[::-1]

In [110]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_50k =  tempo_ordenaçao(arr1_50k)
print(f"Tempo do primeiro array de 50k: {time_arr1_50k} segundos.")
time_arr2_50k = tempo_ordenaçao(arr2_50k)
print(f"Tempo do primeiro array de 50k: {time_arr2_50k} segundos.")
time_arr3_50k = tempo_ordenaçao(arr3_50k)
print(f"Tempo do primeiro array de 50k: {time_arr3_50k} segundos.")
time_wc_50k = tempo_ordenaçao(arr_wc_50k)
print(f"Tempo do primeiro array de 50k: {time_wc_50k} segundos.")

Tempo do primeiro array de 50k: 489.6256580352783 segundos.
Tempo do primeiro array de 50k: 486.37282371520996 segundos.
Tempo do primeiro array de 50k: 496.48219561576843 segundos.
Tempo do primeiro array de 50k: 716.8304123878479 segundos.


In [116]:
# Fazendo uma média dos 3 casos dos arrays aleatórios
list_arr_50k = np.array([time_arr1_50k, time_arr2_50k, time_arr3_50k])
mean_arr_50k = list_arr_50k.mean()
print(f"Tempo médio de ordenação dos arrays aleatórios de 50k: {mean_arr_50k} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 50k: 490.8268924554189 segundos.


## Salvamento dos Dados

In [136]:
# Salvando os tempos de ordenação
np.save("list_arr_1k", list_arr_1k)
np.save("list_arr_5k", list_arr_5k)
np.save("list_arr_10k", list_arr_10k)
np.save("list_arr_20k", list_arr_20k)
np.save("list_arr_30k", list_arr_30k)
np.save("list_arr_40k", list_arr_40k)
np.save("list_arr_50k", list_arr_50k)

In [137]:
# Salvando as médias dos tempos dos arrays aleatórios
np.save("mean_arr_1k", mean_arr_1k)
np.save("mean_arr_5k", mean_arr_5k)
np.save("mean_arr_10k", mean_arr_10k)
np.save("mean_arr_20k", mean_arr_20k)
np.save("mean_arr_30k", mean_arr_30k)
np.save("mean_arr_40k", mean_arr_40k)
np.save("mean_arr_50k", mean_arr_50k)

In [138]:
# Salvando os piores tempos
np.save("time_wc_1k", time_wc_1k)
np.save("time_wc_5k", time_wc_5k)
np.save("time_wc_10k", time_wc_10k)
np.save("time_wc_20k", time_wc_20k)
np.save("time_wc_30k", time_wc_30k)
np.save("time_wc_40k", time_wc_40k)
np.save("time_wc_50k", time_wc_50k)