## Importando as bibliotecas usadas no código

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import time

## Definindo as funções usadas no código

In [3]:
# Definindo a função bubble sort sem lib (obrigatório)
def bubble_sort(arr):
    lista = np.array(arr)
    n = len(lista)
    for i in range(n):
        for j in range(0, n - i - 1):
            if lista[j] > lista[j + 1]:
                lista[j], lista[j + 1] = lista[j + 1], lista[j]

In [4]:
def selection_sort(arr):
    lista = np.array(arr.copy())
    n  = len(lista)
    for j in range(n-1):
        min_index = j
        for i in range(j, n):
            if lista[i] < lista[min_index]:
                min_index = i
        lista[j], lista[min_index] = lista[min_index], lista[j]

In [5]:
def insertion_sort(arr):
    lista = np.array(arr.copy())
    n = len(lista)
    for i in range(n):
        cur = lista[i]
        j = i - 1
        while j >= 0 and lista[j] > cur:
            lista[j+1], lista[j] = lista[j], cur
            j -= 1
    return lista

In [6]:
def shell_sort(arr):
    lista = np.array(arr.copy())
    n = len(lista)
    gap = n // 2
    while gap >= 1:
        for i in range(n):
            cur = lista[i]
            j = i - gap
            while j >= 0 and lista[j] > cur:
                lista[j+gap], lista[j] = lista[j], cur
                j-= gap
        print(lista)
        gap //= 2

In [100]:
def quick_sort(arr):
    lista = arr.copy()
    n = len(lista)
    if len(lista) <= 1:
        return np.array(lista)
    else:
        pivo = lista[n-1]
        menores = [x for x in lista if x < pivo]
        iguais = [x for x in lista if x == pivo]
        maiores = [x for x in lista if x > pivo]
        return np.hstack([quick_sort(menores), iguais, quick_sort(maiores)]).astype(np.int32)

In [8]:
def merge_sort(arr, inicio=0, fim=None):
    lista = arr
    if fim is None:
        fim = len(lista)
    if (fim - inicio) > 1:
        meio = (inicio + fim) // 2
        merge_sort(arr, inicio, meio)
        merge_sort(arr, meio, fim)
        merge(lista, inicio, meio, fim)
    return lista

def merge(arr, inicio, meio, fim):
    lista = arr
    esquerda = lista[inicio:meio].copy()
    direita = lista[meio:fim].copy()
    i = 0
    j = 0 
    # i para esquerda j para direita
    for k in range(inicio, fim):
        if i >= len(esquerda):
            lista[k] = direita[j]
            j += 1
        elif j >= len(direita):
            lista[k] = esquerda[i]
            i += 1
        elif esquerda[i] <= direita[j]:
            lista[k] = esquerda[i]
            i += 1
        elif direita[j] < esquerda[i]: #podia ser else, mas quis ilustrar melhor a condição
            lista[k] = direita[j]
            j += 1

In [9]:
# Definindo as função de retorno dos tempo que o array levou a ser ordenado em cada método
def tempo_ordenaçao_bs(lista):
    start_time = time.time()
    bubble_sort(lista.copy())
    end_time = time.time()
    total_time = end_time - start_time
    return total_time

def tempo_ordenaçao_ss(lista):
    start_time = time.time()
    selection_sort(lista.copy())
    end_time = time.time()
    total_time = end_time - start_time
    return total_time

def tempo_ordenaçao_ins(lista):
    start_time = time.time()
    insertion_sort(lista.copy())
    end_time = time.time()
    total_time = end_time - start_time
    return total_time

def tempo_ordenaçao_sh(lista):
    start_time = time.time()
    shell_sort(lista.copy())
    end_time = time.time()
    total_time = end_time - start_time
    return total_time

def tempo_ordenaçao_qs(lista):
    start_time = time.time()
    quick_sort(lista.copy())
    end_time = time.time()
    total_time = end_time - start_time
    return total_time

def tempo_ordenaçao_ms(lista):
    start_time = time.time()
    merge_sort(lista.copy())
    end_time = time.time()
    total_time = end_time - start_time
    return total_time

## Definindo os arrays

In [10]:
# N = 1k
arr1_1k = np.random.randint(1,1001,1000)
arr2_1k = np.random.randint(1,1001,1000)
arr3_1k = np.random.randint(1,1001,1000)
arr_wc_1k = np.sort(arr1_1k.copy())[::-1]


# N = 10k
arr1_10k = np.random.randint(1,1001,10000)
arr2_10k = np.random.randint(1,1001,10000)
arr3_10k = np.random.randint(1,1001,10000)
arr_wc_10k = np.sort(arr1_10k.copy())[::-1]

# N = 20k
arr1_20k = np.random.randint(1,1001,20000)
arr2_20k = np.random.randint(1,1001,20000)
arr3_20k = np.random.randint(1,1001,20000)
arr_wc_20k = np.sort(arr1_20k.copy())[::-1]

# N = 30k
arr1_30k = np.random.randint(1,1001,30000)
arr2_30k = np.random.randint(1,1001,30000)
arr3_30k = np.random.randint(1,1001,30000)
arr_wc_30k = np.sort(arr1_30k.copy())[::-1]


# N = 40k
arr1_40k = np.random.randint(1,1001,40000)
arr2_40k = np.random.randint(1,1001,40000)
arr3_40k = np.random.randint(1,1001,40000)
arr_wc_40k = np.sort(arr1_40k.copy())[::-1]

# N = 50k
arr1_50k = np.random.randint(1,1001,50000)
arr2_50k = np.random.randint(1,1001,50000)
arr3_50k = np.random.randint(1,1001,50000)
arr_wc_50k = np.sort(arr1_50k.copy())[::-1]


# `Bubble Sort`

## 1. Calculando os tempos de ordenação

In [11]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_1k_bs =  tempo_ordenaçao_bs(arr1_1k)
print(f"Tempo do primeiro array de 1k: {time_arr1_1k_bs} segundos")
time_arr2_1k_bs = tempo_ordenaçao_bs(arr2_1k)
print(f"Tempo do segundo array de 1k: {time_arr2_1k_bs} segundos")
time_arr3_1k_bs = tempo_ordenaçao_bs(arr3_1k)
print(f"Tempo do terceiro array de 1k: {time_arr3_1k_bs} segundos")
time_wc_1k_bs = tempo_ordenaçao_bs(arr_wc_1k)
print(f"Tempo do array de pior caso de 1k: {time_wc_1k_bs} segundos")

Tempo do primeiro array de 1k: 0.18819594383239746 segundos
Tempo do segundo array de 1k: 0.18584918975830078 segundos
Tempo do terceiro array de 1k: 0.1846919059753418 segundos
Tempo do array de pior caso de 1k: 0.27110910415649414 segundos


In [12]:
# Fazendo uma média dos 3 casos dos arrays aleatórios
mean_arr_1k_bs = (time_arr1_1k_bs + time_arr2_1k_bs + time_arr3_1k_bs)/3
list_arr_1k_bs = np.array([time_arr1_1k_bs, time_arr2_1k_bs, time_arr3_1k_bs, time_wc_1k_bs, mean_arr_1k_bs])

In [13]:
time_arr1_10k_bs =  tempo_ordenaçao_bs(arr1_10k.copy())
print(f"Tempo do primeiro array de 10k: {time_arr1_10k_bs} segundos.")
time_arr2_10k_bs = tempo_ordenaçao_bs(arr2_10k.copy())
print(f"Tempo do segundo array de 10k: {time_arr2_10k_bs} segundos.")
time_arr3_10k_bs = tempo_ordenaçao_bs(arr3_10k.copy())
print(f"Tempo do terceiro array de 10k: {time_arr3_10k_bs} segundos.")
time_wc_10k_bs = tempo_ordenaçao_bs(arr_wc_10k.copy())
print(f"Tempo do array de pior caso 10k: {time_wc_10k_bs} segundos.")

Tempo do primeiro array de 10k: 18.747546195983887 segundos.
Tempo do segundo array de 10k: 18.60019540786743 segundos.
Tempo do terceiro array de 10k: 18.797510623931885 segundos.
Tempo do array de pior caso 10k: 27.785470724105835 segundos.


In [14]:
mean_arr_10k_bs = (time_arr1_10k_bs + time_arr2_10k_bs + time_arr3_10k_bs)/3
list_arr_10k_bs = np.array([time_arr1_10k_bs, time_arr2_10k_bs, time_arr3_10k_bs, time_wc_10k_bs, mean_arr_10k_bs])

In [15]:
time_arr1_20k_bs =  tempo_ordenaçao_bs(arr1_20k)
print(f"Tempo do primeiro array de 20k: {time_arr1_20k_bs} segundos.")
time_arr2_20k_bs = tempo_ordenaçao_bs(arr2_20k)
print(f"Tempo do segundo array de 20k: {time_arr2_20k_bs} segundos.")
time_arr3_20k_bs = tempo_ordenaçao_bs(arr3_20k)
print(f"Tempo do terceiro array de 20k: {time_arr3_20k_bs} segundos.")
time_wc_20k_bs = tempo_ordenaçao_bs(arr_wc_20k)
print(f"Tempo do array de pior caso de 20k: {time_wc_20k_bs} segundos.")

Tempo do primeiro array de 20k: 75.03603291511536 segundos.
Tempo do segundo array de 20k: 77.02528142929077 segundos.
Tempo do terceiro array de 20k: 79.38759136199951 segundos.
Tempo do array de pior caso de 20k: 117.49453783035278 segundos.


In [16]:
mean_arr_20k_bs = (time_arr1_20k_bs + time_arr2_20k_bs + time_arr3_20k_bs)/3
list_arr_20k_bs = np.array([time_arr1_20k_bs, time_arr2_20k_bs, time_arr3_20k_bs, time_wc_20k_bs, mean_arr_20k_bs])
print(f"Tempo médio de ordenação dos arrays aleatórios de 20k: {mean_arr_20k_bs} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 20k: 77.14963523546855 segundos.


In [17]:
time_arr1_30k_bs =  tempo_ordenaçao_bs(arr1_30k)
print(f"Tempo do primeiro array de 30k: {time_arr1_30k_bs} segundos.")
time_arr2_30k_bs = tempo_ordenaçao_bs(arr2_30k)
print(f"Tempo do segundo array de 30k: {time_arr2_30k_bs} segundos.")
time_arr3_30k_bs = tempo_ordenaçao_bs(arr3_30k)
print(f"Tempo do terceiro array de 30k: {time_arr3_30k_bs} segundos.")
time_wc_30k_bs = tempo_ordenaçao_bs(arr_wc_30k)
print(f"Tempo do array de pior caso de 30k: {time_wc_30k_bs} segundos.")

Tempo do primeiro array de 30k: 174.37844562530518 segundos.
Tempo do segundo array de 30k: 169.49566745758057 segundos.
Tempo do terceiro array de 30k: 167.75885319709778 segundos.
Tempo do array de pior caso de 30k: 252.9721884727478 segundos.


In [18]:
mean_arr_30k_bs = (time_arr1_30k_bs + time_arr2_30k_bs + time_arr3_30k_bs)/3
list_arr_30k_bs = np.array([time_arr1_30k_bs, time_arr2_30k_bs, time_arr3_30k_bs, time_wc_30k_bs, mean_arr_30k_bs])
print(f"Tempo médio de ordenação dos arrays aleatórios de 30k: {mean_arr_30k_bs} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 30k: 170.54432209332785 segundos.


In [19]:
time_arr1_40k_bs =  tempo_ordenaçao_bs(arr1_40k)
print(f"Tempo do primeiro array de 40k: {time_arr1_40k_bs} segundos.")
time_arr2_40k_bs = tempo_ordenaçao_bs(arr2_40k)
print(f"Tempo do segundo array de 40k: {time_arr2_40k_bs} segundos.")
time_arr3_40k_bs = tempo_ordenaçao_bs(arr3_40k)
print(f"Tempo do terceiro array de 40k: {time_arr3_40k_bs} segundos.")
time_wc_40k_bs = tempo_ordenaçao_bs(arr_wc_40k)
print(f"Tempo do array de pior caso de 40k: {time_wc_40k_bs} segundos.")

Tempo do primeiro array de 40k: 301.660475730896 segundos.
Tempo do segundo array de 40k: 298.87842750549316 segundos.
Tempo do terceiro array de 40k: 302.52314472198486 segundos.
Tempo do array de pior caso de 40k: 455.0111424922943 segundos.


In [20]:
mean_arr_40k_bs = (time_arr1_40k_bs + time_arr2_40k_bs + time_arr3_40k_bs)/3
list_arr_40k_bs = np.array([time_arr1_40k_bs, time_arr2_40k_bs, time_arr3_40k_bs, time_wc_40k_bs, mean_arr_40k_bs])
print(f"Tempo médio de ordenação dos arrays aleatórios de 40k: {mean_arr_40k_bs} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 40k: 301.0206826527913 segundos.


In [21]:
time_arr1_50k_bs =  tempo_ordenaçao_bs(arr1_50k)
print(f"Tempo do primeiro array de 50k: {time_arr1_50k_bs} segundos.")
time_arr2_50k_bs = tempo_ordenaçao_bs(arr2_50k)
print(f"Tempo do segundo array de 50k: {time_arr2_50k_bs} segundos.")
time_arr3_50k_bs = tempo_ordenaçao_bs(arr3_50k)
print(f"Tempo do terceiro array de 50k: {time_arr3_50k_bs} segundos.")
time_wc_50k_bs = tempo_ordenaçao_bs(arr_wc_50k)
print(f"Tempo do array de pior caso de 50k: {time_wc_50k_bs} segundos.")

Tempo do primeiro array de 50k: 483.7685377597809 segundos.
Tempo do segundo array de 50k: 481.30278420448303 segundos.
Tempo do terceiro array de 50k: 481.320437669754 segundos.
Tempo do array de pior caso de 50k: 723.127551317215 segundos.


In [22]:
mean_arr_50k_bs = (time_arr1_50k_bs + time_arr2_50k_bs + time_arr3_50k_bs)/3
list_arr_50k_bs = np.array([time_arr1_50k_bs, time_arr2_50k_bs, time_arr3_50k_bs, time_wc_50k_bs, mean_arr_50k_bs])
print(f"Tempo médio de ordenação dos arrays aleatórios de 50k: {mean_arr_50k_bs} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 50k: 482.13058654467267 segundos.


## 2. Fazendo as listas de tempos e médias do método

In [23]:
list_bs = np.array([list_arr_1k_bs, list_arr_10k_bs, list_arr_20k_bs,
                    list_arr_30k_bs, list_arr_40k_bs, list_arr_50k_bs])

## 3. Salvando os Dados

In [24]:
# Salvando os tempos de ordenação
np.save("list_bs", list_bs)

## `Selection Sort`

## 1. Calculando os tempos de ordenação

In [25]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_1k_ss =  tempo_ordenaçao_ss(arr1_1k)
print(f"Tempo do primeiro array de 1k: {time_arr1_1k_ss} segundos")
time_arr2_1k_ss = tempo_ordenaçao_ss(arr2_1k)
print(f"Tempo do segundo array de 1k: {time_arr2_1k_ss} segundos")
time_arr3_1k_ss = tempo_ordenaçao_ss(arr3_1k)
print(f"Tempo do terceiro array de 1k: {time_arr3_1k_ss} segundos")
time_wc_1k_ss = tempo_ordenaçao_ss(arr_wc_1k)
print(f"Tempo do array de pior caso de 1k: {time_wc_1k_ss} segundos")

Tempo do primeiro array de 1k: 0.12608742713928223 segundos
Tempo do segundo array de 1k: 0.09774303436279297 segundos
Tempo do terceiro array de 1k: 0.09425210952758789 segundos
Tempo do array de pior caso de 1k: 0.11908626556396484 segundos


In [26]:
# Fazendo uma média dos 3 casos dos arrays aleatórios
mean_arr_1k_ss = (time_arr1_1k_ss + time_arr2_1k_ss + time_arr3_1k_ss)/3
list_arr_1k_ss = np.array([time_arr1_1k_ss, time_arr2_1k_ss, time_arr3_1k_ss, time_wc_1k_ss, mean_arr_1k_ss])
print(f"Tempo médio de ordenação dos arrays de 1k: {mean_arr_1k_ss} segundos.")

Tempo médio de ordenação dos arrays de 1k: 0.10602752367655437 segundos.


In [27]:
time_arr1_10k_ss =  tempo_ordenaçao_ss(arr1_10k.copy())
print(f"Tempo do primeiro array de 10k: {time_arr1_10k_ss} segundos.")
time_arr2_10k_ss = tempo_ordenaçao_ss(arr2_10k.copy())
print(f"Tempo do segundo array de 10k: {time_arr2_10k_ss} segundos.")
time_arr3_10k_ss = tempo_ordenaçao_ss(arr3_10k.copy())
print(f"Tempo do terceiro array de 10k: {time_arr3_10k_ss} segundos.")
time_wc_10k_ss = tempo_ordenaçao_ss(arr_wc_10k.copy())
print(f"Tempo do array de pior caso 10k: {time_wc_10k_ss} segundos.")

Tempo do primeiro array de 10k: 9.443545818328857 segundos.
Tempo do segundo array de 10k: 9.44372844696045 segundos.
Tempo do terceiro array de 10k: 9.400574684143066 segundos.
Tempo do array de pior caso 10k: 9.444650411605835 segundos.


In [28]:
mean_arr_10k_ss = (time_arr1_10k_ss + time_arr2_10k_ss + time_arr3_10k_ss)/3
list_arr_10k_ss = np.array([time_arr1_10k_ss, time_arr2_10k_ss, time_arr3_10k_ss, time_wc_10k_ss, mean_arr_10k_ss])
print(f"Tempo médio de ordenação dos arrays aleatórios de 10k: {mean_arr_10k_ss} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 10k: 9.429282983144125 segundos.


In [29]:
time_arr1_20k_ss =  tempo_ordenaçao_ss(arr1_20k.copy())
print(f"Tempo do primeiro array de 20k: {time_arr1_20k_ss} segundos.")
time_arr2_20k_ss = tempo_ordenaçao_ss(arr2_20k.copy())
print(f"Tempo do segundo array de 20k: {time_arr2_20k_ss} segundos.")
time_arr3_20k_ss = tempo_ordenaçao_ss(arr3_20k.copy())
print(f"Tempo do terceiro array de 20k: {time_arr3_20k_ss} segundos.")
time_wc_20k_ss = tempo_ordenaçao_ss(arr_wc_20k.copy())
print(f"Tempo do array de pior caso 20k: {time_wc_20k_ss} segundos.")

Tempo do primeiro array de 20k: 39.03969407081604 segundos.
Tempo do segundo array de 20k: 36.8493070602417 segundos.
Tempo do terceiro array de 20k: 37.11615777015686 segundos.
Tempo do array de pior caso 20k: 37.05158066749573 segundos.


In [30]:
mean_arr_20k_ss = (time_arr1_20k_ss + time_arr2_20k_ss + time_arr3_20k_ss)/3
list_arr_20k_ss = np.array([time_arr1_20k_ss, time_arr2_20k_ss, time_arr3_20k_ss, time_wc_20k_ss, mean_arr_20k_ss])
print(f"Tempo médio de ordenação dos arrays aleatórios de 20k: {mean_arr_20k_ss} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 20k: 37.66838630040487 segundos.


In [31]:
time_arr1_30k_ss =  tempo_ordenaçao_ss(arr1_30k.copy())
print(f"Tempo do primeiro array de 30k: {time_arr1_30k_ss} segundos.")
time_arr2_30k_ss = tempo_ordenaçao_ss(arr2_30k.copy())
print(f"Tempo do segundo array de 30k: {time_arr2_30k_ss} segundos.")
time_arr3_30k_ss = tempo_ordenaçao_ss(arr3_30k.copy())
print(f"Tempo do terceiro array de 30k: {time_arr3_30k_ss} segundos.")
time_wc_30k_ss = tempo_ordenaçao_ss(arr_wc_30k.copy())
print(f"Tempo do array de pior caso 30k: {time_wc_30k_ss} segundos.")

Tempo do primeiro array de 30k: 89.29061126708984 segundos.
Tempo do segundo array de 30k: 85.9563193321228 segundos.
Tempo do terceiro array de 30k: 82.75230360031128 segundos.
Tempo do array de pior caso 30k: 82.75889706611633 segundos.


In [32]:
mean_arr_30k_ss = (time_arr1_30k_ss + time_arr2_30k_ss + time_arr3_30k_ss)/3
list_arr_30k_ss = np.array([time_arr1_30k_ss, time_arr2_30k_ss, time_arr3_30k_ss, time_wc_30k_ss, mean_arr_30k_ss])
print(f"Tempo médio de ordenação dos arrays aleatórios de 30k: {mean_arr_30k_ss} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 30k: 85.99974473317464 segundos.


In [33]:
time_arr1_40k_ss =  tempo_ordenaçao_ss(arr1_40k.copy())
print(f"Tempo do primeiro array de 40k: {time_arr1_40k_ss} segundos.")
time_arr2_40k_ss = tempo_ordenaçao_ss(arr2_40k.copy())
print(f"Tempo do segundo array de 40k: {time_arr2_40k_ss} segundos.")
time_arr3_40k_ss = tempo_ordenaçao_ss(arr3_40k.copy())
print(f"Tempo do terceiro array de 40k: {time_arr3_40k_ss} segundos.")
time_wc_40k_ss = tempo_ordenaçao_ss(arr_wc_40k.copy())
print(f"Tempo do array de pior caso 40k: {time_wc_40k_ss} segundos.")

Tempo do primeiro array de 40k: 146.34447407722473 segundos.
Tempo do segundo array de 40k: 146.41780948638916 segundos.
Tempo do terceiro array de 40k: 146.15342378616333 segundos.
Tempo do array de pior caso 40k: 146.4808690547943 segundos.


In [34]:
mean_arr_40k_ss = (time_arr1_40k_ss + time_arr2_40k_ss + time_arr3_40k_ss)/3
list_arr_40k_ss = np.array([time_arr1_40k_ss, time_arr2_40k_ss, time_arr3_40k_ss, time_wc_40k_ss, mean_arr_40k_ss])
print(f"Tempo médio de ordenação dos arrays aleatórios de 40k: {mean_arr_40k_ss} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 40k: 146.30523578325906 segundos.


In [35]:
time_arr1_50k_ss =  tempo_ordenaçao_ss(arr1_50k.copy())
print(f"Tempo do primeiro array de 50k: {time_arr1_50k_ss} segundos.")
time_arr2_50k_ss = tempo_ordenaçao_ss(arr2_50k.copy())
print(f"Tempo do segundo array de 50k: {time_arr2_50k_ss} segundos.")
time_arr3_50k_ss = tempo_ordenaçao_ss(arr3_50k.copy())
print(f"Tempo do terceiro array de 50k: {time_arr3_50k_ss} segundos.")
time_wc_50k_ss = tempo_ordenaçao_ss(arr_wc_50k.copy())
print(f"Tempo do array de pior caso de 50k: {time_wc_50k_ss} segundos.")

Tempo do primeiro array de 50k: 228.06460452079773 segundos.
Tempo do segundo array de 50k: 231.28575658798218 segundos.
Tempo do terceiro array de 50k: 230.8803207874298 segundos.
Tempo do array de pior caso de 50k: 229.8295714855194 segundos.


In [36]:
mean_arr_50k_ss = (time_arr1_50k_ss + time_arr2_50k_ss + time_arr3_50k_ss)/3
list_arr_50k_ss = np.array([time_arr1_50k_ss, time_arr2_50k_ss, time_arr3_50k_ss, time_wc_50k_ss, mean_arr_50k_ss])
print(f"Tempo médio de ordenação dos arrays aleatórios de 50k: {mean_arr_50k_ss} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 50k: 230.07689396540323 segundos.


## 2. Fazendo as listas de tempos e médias do método

In [37]:
list_ss = np.array([list_arr_1k_ss, list_arr_10k_ss, list_arr_20k_ss,
                        list_arr_30k_ss, list_arr_40k_ss, list_arr_50k_ss])


## 3. Salvando os Dados

In [38]:
np.save("list_ss", list_ss)

## `Insertion Sort`

## 1. Calculando os tempos de ordenação

In [39]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_1k_ins =  tempo_ordenaçao_ins(arr1_1k.copy())
print(f"Tempo do primeiro array de 1k: {time_arr1_1k_ins} segundos")
time_arr2_1k_ins = tempo_ordenaçao_ins(arr2_1k.copy())
print(f"Tempo do segundo array de 1k: {time_arr2_1k_ins} segundos")
time_arr3_1k_ins = tempo_ordenaçao_ins(arr3_1k.copy())
print(f"Tempo do terceiro array de 1k: {time_arr3_1k_ins} segundos")
time_wc_1k_ins = tempo_ordenaçao_ins(arr_wc_1k.copy())
print(f"Tempo do array de pior caso de 1k: {time_wc_1k_ins} segundos")

Tempo do primeiro array de 1k: 0.10362696647644043 segundos
Tempo do segundo array de 1k: 0.09655094146728516 segundos
Tempo do terceiro array de 1k: 0.0996546745300293 segundos
Tempo do array de pior caso de 1k: 0.21695494651794434 segundos


In [40]:
# Fazendo uma média dos 3 casos dos arrays aleatórios (1k)
mean_arr_1k_ins = (time_arr1_1k_ins + time_arr2_1k_ins + time_arr3_1k_ins)/3
list_arr_1k_ins = np.array([time_arr1_1k_ins, time_arr2_1k_ins, time_arr3_1k_ins, time_wc_1k_ins, mean_arr_1k_ins])
print(f"Tempo médio de ordenação dos arrays de 1k: {mean_arr_1k_ins} segundos.")

Tempo médio de ordenação dos arrays de 1k: 0.09994419415791829 segundos.


In [41]:
time_arr1_10k_ins =  tempo_ordenaçao_ins(arr1_10k.copy())
print(f"Tempo do primeiro array de 10k: {time_arr1_10k_ins} segundos.")
time_arr2_10k_ins = tempo_ordenaçao_ins(arr2_10k.copy())
print(f"Tempo do segundo array de 10k: {time_arr2_10k_ins} segundos.")
time_arr3_10k_ins = tempo_ordenaçao_ins(arr3_10k.copy())
print(f"Tempo do terceiro array de 10k: {time_arr3_10k_ins} segundos.")
time_wc_10k_ins = tempo_ordenaçao_ins(arr_wc_10k.copy())
print(f"Tempo do array de pior caso 10k: {time_wc_10k_ins} segundos.")

Tempo do primeiro array de 10k: 10.187601804733276 segundos.
Tempo do segundo array de 10k: 10.117457628250122 segundos.
Tempo do terceiro array de 10k: 10.270274639129639 segundos.
Tempo do array de pior caso 10k: 21.602692127227783 segundos.


In [42]:
mean_arr_10k_ins = (time_arr1_10k_ins + time_arr2_10k_ins + time_arr3_10k_ins)/3
list_arr_10k_ins = np.array([time_arr1_10k_ins, time_arr2_10k_ins, time_arr3_10k_ins, time_wc_10k_ins, mean_arr_10k_ins])
print(f"Tempo médio de ordenação dos arrays aleatórios de 10k: {mean_arr_10k_ins} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 10k: 10.19177802403768 segundos.


In [43]:
time_arr1_20k_ins =  tempo_ordenaçao_ins(arr1_20k.copy())
print(f"Tempo do primeiro array de 20k: {time_arr1_20k_ins} segundos.")
time_arr2_20k_ins = tempo_ordenaçao_ins(arr2_20k.copy())
print(f"Tempo do segundo array de 20k: {time_arr2_20k_ins} segundos.")
time_arr3_20k_ins = tempo_ordenaçao_ins(arr3_20k.copy())
print(f"Tempo do terceiro array de 20k: {time_arr3_20k_ins} segundos.")
time_wc_20k_ins = tempo_ordenaçao_ins(arr_wc_20k.copy())
print(f"Tempo do array de pior caso 20k: {time_wc_20k_ins} segundos.")

Tempo do primeiro array de 20k: 41.135894775390625 segundos.
Tempo do segundo array de 20k: 41.36989998817444 segundos.
Tempo do terceiro array de 20k: 40.7199490070343 segundos.
Tempo do array de pior caso 20k: 81.88720273971558 segundos.


In [44]:
mean_arr_20k_ins = (time_arr1_20k_ins + time_arr2_20k_ins + time_arr3_20k_ins)/3
list_arr_20k_ins = np.array([time_arr1_20k_ins, time_arr2_20k_ins, time_arr3_20k_ins, time_wc_20k_ins, mean_arr_20k_ins])
print(f"Tempo médio de ordenação dos arrays aleatórios de 20k: {mean_arr_20k_ins} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 20k: 41.07524792353312 segundos.


In [45]:
time_arr1_30k_ins =  tempo_ordenaçao_ins(arr1_30k.copy())
print(f"Tempo do primeiro array de 30k: {time_arr1_30k_ins} segundos.")
time_arr2_30k_ins = tempo_ordenaçao_ins(arr2_30k.copy())
print(f"Tempo do segundo array de 30k: {time_arr2_30k_ins} segundos.")
time_arr3_30k_ins = tempo_ordenaçao_ins(arr3_30k.copy())
print(f"Tempo do terceiro array de 30k: {time_arr3_30k_ins} segundos.")
time_wc_30k_ins = tempo_ordenaçao_ins(arr_wc_30k.copy())
print(f"Tempo do array de pior caso 30k: {time_wc_30k_ins} segundos.")

Tempo do primeiro array de 30k: 92.39896965026855 segundos.
Tempo do segundo array de 30k: 92.27633547782898 segundos.
Tempo do terceiro array de 30k: 91.77691054344177 segundos.
Tempo do array de pior caso 30k: 182.81697964668274 segundos.


In [46]:
mean_arr_30k_ins = (time_arr1_30k_ins + time_arr2_30k_ins + time_arr3_30k_ins)/3
list_arr_30k_ins = np.array([time_arr1_30k_ins, time_arr2_30k_ins, time_arr3_30k_ins, time_wc_30k_ins, mean_arr_30k_ins])
print(f"Tempo médio de ordenação dos arrays aleatórios de 30k: {mean_arr_30k_ins} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 30k: 92.15073855717976 segundos.


In [47]:
time_arr1_40k_ins =  tempo_ordenaçao_ins(arr1_40k.copy())
print(f"Tempo do primeiro array de 40k: {time_arr1_40k_ins} segundos.")
time_arr2_40k_ins = tempo_ordenaçao_ins(arr2_40k.copy())
print(f"Tempo do segundo array de 40k: {time_arr2_40k_ins} segundos.")
time_arr3_40k_ins = tempo_ordenaçao_ins(arr3_40k.copy())
print(f"Tempo do terceiro array de 40k: {time_arr3_40k_ins} segundos.")
time_wc_40k_ins = tempo_ordenaçao_ins(arr_wc_40k.copy())
print(f"Tempo do array de pior caso 40k: {time_wc_40k_ins} segundos.")

Tempo do primeiro array de 40k: 162.925922870636 segundos.
Tempo do segundo array de 40k: 162.3971767425537 segundos.
Tempo do terceiro array de 40k: 163.33387541770935 segundos.
Tempo do array de pior caso 40k: 327.82256746292114 segundos.


In [48]:
mean_arr_40k_ins = (time_arr1_40k_ins + time_arr2_40k_ins + time_arr3_40k_ins)/3
list_arr_40k_ins = np.array([time_arr1_40k_ins, time_arr2_40k_ins, time_arr3_40k_ins, time_wc_40k_ins, mean_arr_40k_ins])
print(f"Tempo médio de ordenação dos arrays aleatórios de 40k: {mean_arr_40k_ins} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 40k: 162.88565834363303 segundos.


In [49]:
time_arr1_50k_ins =  tempo_ordenaçao_ins(arr1_50k.copy())
print(f"Tempo do primeiro array de 50k: {time_arr1_50k_ins} segundos.")
time_arr2_50k_ins = tempo_ordenaçao_ins(arr2_50k.copy())
print(f"Tempo do segundo array de 50k: {time_arr2_50k_ins} segundos.")
time_arr3_50k_ins = tempo_ordenaçao_ins(arr3_50k.copy())
print(f"Tempo do terceiro array de 50k: {time_arr3_50k_ins} segundos.")
time_wc_50k_ins = tempo_ordenaçao_ins(arr_wc_50k.copy())
print(f"Tempo do array de pior caso de 50k: {time_wc_50k_ins} segundos.")

Tempo do primeiro array de 50k: 256.25266098976135 segundos.
Tempo do segundo array de 50k: 253.80666422843933 segundos.
Tempo do terceiro array de 50k: 255.68561148643494 segundos.
Tempo do array de pior caso de 50k: 511.87695121765137 segundos.


In [50]:
mean_arr_50k_ins = (time_arr1_50k_ins + time_arr2_50k_ins + time_arr3_50k_ins)/3
list_arr_50k_ins = np.array([time_arr1_50k_ins, time_arr2_50k_ins, time_arr3_50k_ins, time_wc_50k_ins, mean_arr_50k_ins])
print(f"Tempo médio de ordenação dos arrays aleatórios de 50k: {mean_arr_50k_ins} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 50k: 255.24831223487854 segundos.


## 2. Fazendo as listas de tempos e médias do método

In [51]:
# Definição das variáveis _ins
list_ins = np.array([list_arr_1k_ins, list_arr_10k_ins, list_arr_20k_ins,
                    list_arr_30k_ins, list_arr_40k_ins, list_arr_50k_ins])


## 3. Salvando os Dados

In [52]:
# Comandos para salvar os arrays _ins
np.save("list_ins", list_ins)

## `Shell Sort`

## 1. Calculando os tempos de ordenação

In [53]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_1k_sh =  tempo_ordenaçao_sh(arr1_1k.copy())
print(f"Tempo do primeiro array de 1k: {time_arr1_1k_sh} segundos")
time_arr2_1k_sh = tempo_ordenaçao_sh(arr2_1k.copy())
print(f"Tempo do segundo array de 1k: {time_arr2_1k_sh} segundos")
time_arr3_1k_sh = tempo_ordenaçao_sh(arr3_1k.copy())
print(f"Tempo do terceiro array de 1k: {time_arr3_1k_sh} segundos")
time_wc_1k_sh = tempo_ordenaçao_sh(arr_wc_1k.copy())
print(f"Tempo do array de pior caso de 1k: {time_wc_1k_sh} segundos")

[458 280 300  89 836   5 341 128 356 247  33 498 429 401 227 650  43 160
 157 123  48 571 363 401 506 606 199 541 230 273 138  51   4 260 246 355
 928 227 110 840 722 326 208 404 209  19 200 179 303 574 382  53 725 463
 327 145  84 715 199 373 436 117 276 123 168 623 532 333 652 440 152  88
 920 422 191 333 790 296  10 265 587   9 335  35 614 447  74 670 297 787
  89 265 616 590 330 144 146 176 351 299 649 350 555 273 454 431  65 252
 409 635 226 565 179 558 483   6 310   5  58 422 391 355 157 765  30 624
  99 107 145 133 383 614 477 155  27 645 152 434  82 343 812  46 365 593
 472 528 518 316 233 313 670 627 364 167 838 404 244 282 138  62 528 328
 486 159 540 205 611 206 665  63 678 289 358 422 621 225 128 400  63 443
 188 611 410  95 105 333 216 700 573 523 167 155  37 189 364 106 378  46
 440 318  75 399 526 362 467 480  37 648 621  21  26 226 302 219 190  13
 487  59   9 365 509 486 707 592 612 256 213 399 278 287 341 310  92 402
 320 721 216  19 232  95 428  38 126 106 928 749  9

In [54]:
# Fazendo uma média dos 3 casos dos arrays aleatórios (1k)
mean_arr_1k_sh = (time_arr1_1k_sh + time_arr2_1k_sh + time_arr3_1k_sh)/3
list_arr_1k_sh = np.array([time_arr1_1k_sh, time_arr2_1k_sh, time_arr3_1k_sh, time_wc_1k_sh, mean_arr_1k_sh])
print(f"Tempo médio de ordenação dos arrays de 1k: {mean_arr_1k_sh} segundos.")

Tempo médio de ordenação dos arrays de 1k: 0.021164655685424805 segundos.


In [55]:
time_arr1_10k_sh =  tempo_ordenaçao_sh(arr1_10k.copy())
print(f"Tempo do primeiro array de 10k: {time_arr1_10k_sh} segundos.")
time_arr2_10k_sh = tempo_ordenaçao_sh(arr2_10k.copy())
print(f"Tempo do segundo array de 10k: {time_arr2_10k_sh} segundos.")
time_arr3_10k_sh = tempo_ordenaçao_sh(arr3_10k.copy())
print(f"Tempo do terceiro array de 10k: {time_arr3_10k_sh} segundos.")
time_wc_10k_sh = tempo_ordenaçao_sh(arr_wc_10k.copy())
print(f"Tempo do array de pior caso 10k: {time_wc_10k_sh} segundos.")

[ 54 618 742 ... 995 778 653]
[ 54 211 414 ... 995 871 653]
[ 24 211 278 ... 995 963 932]
[ 24 155 278 ... 995 963 932]
[ 24  53  42 ... 995 978 963]
[ 24   7  21 ... 995 978 990]
[  5   7  21 ... 998 990 990]
[  3   7   4 ... 999 995 990]
[   3    3    4 ... 1000  995  999]
[   1    1    2 ... 1000  999  999]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
Tempo do primeiro array de 10k: 0.08262324333190918 segundos.
[124 678 169 ... 111 706 360]
[ 79 129  41 ... 445 818 802]
[ 79 129  36 ... 746 889 884]
[ 39 129  36 ... 918 889 918]
[ 24  27  12 ... 921 978 989]
[  4  27  12 ... 969 978 989]
[  4   1   9 ... 998 994 996]
[  2   1   5 ... 998 999 996]
[   2    1    2 ...  998 1000 1000]
[   1    1    1 ...  999 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
Tempo do segundo array de 10k: 0.09962153434753418 segundos.
[546 353 268 ... 265 888 931]
[187 35

In [56]:
mean_arr_10k_sh = (time_arr1_10k_sh + time_arr2_10k_sh + time_arr3_10k_sh)/3
list_arr_10k_sh = np.array([time_arr1_10k_sh, time_arr2_10k_sh, time_arr3_10k_sh, time_wc_10k_sh, mean_arr_10k_sh])
print(f"Tempo médio de ordenação dos arrays aleatórios de 10k: {mean_arr_10k_sh} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 10k: 0.08876307805379231 segundos.


In [57]:
time_arr1_20k_sh =  tempo_ordenaçao_sh(arr1_20k.copy())
print(f"Tempo do primeiro array de 20k: {time_arr1_20k_sh} segundos.")
time_arr2_20k_sh = tempo_ordenaçao_sh(arr2_20k.copy())
print(f"Tempo do segundo array de 20k: {time_arr2_20k_sh} segundos.")
time_arr3_20k_sh = tempo_ordenaçao_sh(arr3_20k.copy())
print(f"Tempo do terceiro array de 20k: {time_arr3_20k_sh} segundos.")
time_wc_20k_sh = tempo_ordenaçao_sh(arr_wc_20k.copy())
print(f"Tempo do array de pior caso 20k: {time_wc_20k_sh} segundos.")

[499 206 625 ... 419 732 491]
[  3 206 505 ... 419 821 803]
[  3 206 240 ... 502 821 889]
[  3 144  63 ... 982 974 889]
[  3  20  41 ... 992 999 966]
[  3  10  19 ... 995 999 986]
[  3  10   5 ... 995 999 986]
[  3   5   5 ... 999 999 986]
[   3    3    4 ...  999 1000  997]
[   2    1    1 ... 1000 1000  999]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
Tempo do primeiro array de 20k: 0.20514869689941406 segundos.
[420 553 461 ... 727 406 463]
[418 418 235 ... 981 780 497]
[287  30  56 ... 981 803 888]
[  61   30   56 ...  981  989 1000]
[  16   30   47 ...  981  989 1000]
[  16    9    9 ... 1000  989 1000]
[  13    8    9 ... 1000  993 1000]
[   2    1    7 ... 1000  993 1000]
[   2    1    2 ... 1000  994 1000]
[   2    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 10

In [58]:
mean_arr_20k_sh = (time_arr1_20k_sh + time_arr2_20k_sh + time_arr3_20k_sh)/3
list_arr_20k_sh = np.array([time_arr1_20k_sh, time_arr2_20k_sh, time_arr3_20k_sh, time_wc_20k_sh, mean_arr_20k_sh])
print(f"Tempo médio de ordenação dos arrays aleatórios de 20k: {mean_arr_20k_sh} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 20k: 0.20212801297505698 segundos.


In [59]:
time_arr1_30k_sh =  tempo_ordenaçao_sh(arr1_30k.copy())
print(f"Tempo do primeiro array de 30k: {time_arr1_30k_sh} segundos.")
time_arr2_30k_sh = tempo_ordenaçao_sh(arr2_30k.copy())
print(f"Tempo do segundo array de 30k: {time_arr2_30k_sh} segundos.")
time_arr3_30k_sh = tempo_ordenaçao_sh(arr3_30k.copy())
print(f"Tempo do terceiro array de 30k: {time_arr3_30k_sh} segundos.")
time_wc_30k_sh = tempo_ordenaçao_sh(arr_wc_30k.copy())
print(f"Tempo do array de pior caso 30k: {time_wc_30k_sh} segundos.")

[684 800 546 ... 902 255 783]
[351 757 546 ... 902 535 783]
[224 137 287 ... 966 964 783]
[170  30  11 ... 966 964 783]
[ 27  30  11 ... 996 964 963]
[  4   8  11 ... 996 972 996]
[  2   8   3 ... 996 990 996]
[   2    8    3 ... 1000  998  996]
[   1    1    2 ... 1000  998 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
Tempo do primeiro array de 30k: 0.311570405960083 segundos.
[359 342 194 ... 686 623 832]
[326 112 155 ... 728 856 832]
[ 49 112 155 ... 898 899 832]
[ 49  74  42 ... 898 899 993]
[ 49  10  38 ... 955 988 993]
[ 21  10  38 ... 976 988 993]
[ 12  10  15 ... 997 994 994]
[ 12  10   4 ... 997 994 999]
[   2    3    1 ...  999  999 1000]
[   2    1    1 ... 1000  999 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
Tempo do segundo array

In [60]:
mean_arr_30k_sh = (time_arr1_30k_sh + time_arr2_30k_sh + time_arr3_30k_sh)/3
list_arr_30k_sh = np.array([time_arr1_30k_sh, time_arr2_30k_sh, time_arr3_30k_sh, time_wc_30k_sh, mean_arr_30k_sh])
print(f"Tempo médio de ordenação dos arrays aleatórios de 30k: {mean_arr_30k_sh} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 30k: 0.3130022684733073 segundos.


In [61]:
time_arr1_40k_sh =  tempo_ordenaçao_sh(arr1_40k.copy())
print(f"Tempo do primeiro array de 40k: {time_arr1_40k_sh} segundos.")
time_arr2_40k_sh = tempo_ordenaçao_sh(arr2_40k.copy())
print(f"Tempo do segundo array de 40k: {time_arr2_40k_sh} segundos.")
time_arr3_40k_sh = tempo_ordenaçao_sh(arr3_40k.copy())
print(f"Tempo do terceiro array de 40k: {time_arr3_40k_sh} segundos.")
time_wc_40k_sh = tempo_ordenaçao_sh(arr_wc_40k.copy())
print(f"Tempo do array de pior caso 40k: {time_wc_40k_sh} segundos.")

[285 412 173 ... 606 205 686]
[285 255 173 ... 606 304 811]
[285  67 173 ... 983 939 963]
[285  36  65 ... 983 939 963]
[ 30  36  48 ... 983 939 998]
[  30   11   44 ...  995  963 1000]
[   2    2   14 ...  995  999 1000]
[   2    2    2 ... 1000 1000 1000]
[   2    2    2 ... 1000 1000 1000]
[   2    2    2 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
Tempo do primeiro array de 40k: 0.4369690418243408 segundos.
[110  64  82 ... 262 818 867]
[ 15  64  82 ... 262 985 867]
[ 15  22  82 ... 509 985 867]
[ 15  22   2 ... 989 985 984]
[ 15  22   2 ... 989 985 984]
[ 15   4   2 ... 991 985 984]
[  4   4   2 ... 993 991 994]
[   4    1    2 ... 1000 1000  998]
[   2    1    2 ... 1000 1000  998]
[   2    1    2 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[  

In [62]:
mean_arr_40k_sh = (time_arr1_40k_sh + time_arr2_40k_sh + time_arr3_40k_sh)/3
list_arr_40k_sh = np.array([time_arr1_40k_sh, time_arr2_40k_sh, time_arr3_40k_sh, time_wc_40k_sh, mean_arr_40k_sh])
print(f"Tempo médio de ordenação dos arrays aleatórios de 40k: {mean_arr_40k_sh} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 40k: 0.4537923336029053 segundos.


In [63]:
time_arr1_50k_sh =  tempo_ordenaçao_sh(arr1_50k.copy())
print(f"Tempo do primeiro array de 50k: {time_arr1_50k_sh} segundos.")
time_arr2_50k_sh = tempo_ordenaçao_sh(arr2_50k.copy())
print(f"Tempo do segundo array de 50k: {time_arr2_50k_sh} segundos.")
time_arr3_50k_sh = tempo_ordenaçao_sh(arr3_50k.copy())
print(f"Tempo do terceiro array de 50k: {time_arr3_50k_sh} segundos.")
time_wc_50k_sh = tempo_ordenaçao_sh(arr_wc_50k.copy())
print(f"Tempo do array de pior caso de 50k: {time_wc_50k_sh} segundos.")

[320 338 387 ... 563 666 810]
[ 91  81  60 ... 704 670 906]
[ 17  81  60 ... 769 950 984]
[ 17  27  60 ... 859 950 984]
[ 17  27  22 ... 996 966 991]
[ 17  13   2 ... 996 970 991]
[  7  13   2 ... 996 993 991]
[  7   1   2 ... 996 999 999]
[   1    1    1 ...  999 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 1000]
Tempo do primeiro array de 50k: 0.5436928272247314 segundos.
[585 192 166 ... 754 537 635]
[ 56  72 166 ... 754 579 635]
[  5  72 166 ... 917 579 840]
[  5  72  24 ... 981 961 848]
[  5  25  24 ... 981 990 923]
[  5  23   1 ... 981 990 993]
[  1   3   1 ... 990 997 997]
[  1   3   1 ... 990 999 997]
[  1   3   1 ... 997 999 999]
[   1    2    1 ...  999  999 1000]
[   1    2    1 ... 1000  999 1000]
[   1    1    1 ... 1000  999 1000]
[   1    1    1 ... 1000 1000 1000]
[   1    1    1 ... 1000 1000 100

In [64]:
mean_arr_50k_sh = (time_arr1_50k_sh + time_arr2_50k_sh + time_arr3_50k_sh)/3
list_arr_50k_sh = np.array([time_arr1_50k_sh, time_arr2_50k_sh, time_arr3_50k_sh, time_wc_50k_sh, mean_arr_50k_sh])
print(f"Tempo médio de ordenação dos arrays aleatórios de 50k: {mean_arr_50k_sh} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 50k: 0.54966139793396 segundos.


## 2. Fazendo as listas de tempos e médias do método

In [65]:
list_sh = np.array([list_arr_1k_sh, list_arr_10k_sh, list_arr_20k_sh,
                    list_arr_30k_sh, list_arr_40k_sh, list_arr_50k_sh])

## 3. Salvando os Dados

In [66]:
np.save("list_sh", list_sh)

## `Quick Sort`

## 1. Calculando os tempos de ordenação

In [115]:
time_arr1_1k_qs =  tempo_ordenaçao_qs(arr1_1k.copy())
print(f"Tempo do primeiro array de 1k: {time_arr1_1k_qs} segundos")
time_arr2_1k_qs = tempo_ordenaçao_qs(arr2_1k.copy())
print(f"Tempo do segundo array de 1k: {time_arr2_1k_qs} segundos")
time_arr3_1k_qs = tempo_ordenaçao_qs(arr3_1k.copy())
print(f"Tempo do terceiro array de 1k: {time_arr3_1k_qs} segundos")
time_wc_1k_qs = tempo_ordenaçao_qs(arr_wc_1k.copy())
print(f"Tempo do array de pior caso de 1k: {time_wc_1k_qs} segundos")

Tempo do primeiro array de 1k: 0.0030074119567871094 segundos
Tempo do segundo array de 1k: 0.00453495979309082 segundos
Tempo do terceiro array de 1k: 0.004008293151855469 segundos
Tempo do array de pior caso de 1k: 0.04637479782104492 segundos


In [116]:
# Fazendo uma média dos 3 casos dos arrays aleatórios (1k)
mean_arr_1k_qs = (time_arr1_1k_qs + time_arr2_1k_qs + time_arr3_1k_qs)/3
list_arr_1k_qs = np.array([time_arr1_1k_qs, time_arr2_1k_qs, time_arr3_1k_qs, time_wc_1k_qs, mean_arr_1k_qs])
print(f"Tempo médio de ordenação dos arrays de 1k: {mean_arr_1k_qs} segundos.")

Tempo médio de ordenação dos arrays de 1k: 0.003850221633911133 segundos.


In [117]:
time_arr1_10k_qs =  tempo_ordenaçao_qs(arr1_10k.copy())
print(f"Tempo do primeiro array de 10k: {time_arr1_10k_qs} segundos.")
time_arr2_10k_qs = tempo_ordenaçao_qs(arr2_10k.copy())
print(f"Tempo do segundo array de 10k: {time_arr2_10k_qs} segundos.")
time_arr3_10k_qs = tempo_ordenaçao_qs(arr3_10k.copy())
print(f"Tempo do terceiro array de 10k: {time_arr3_10k_qs} segundos.")
time_wc_10k_qs = tempo_ordenaçao_qs(arr_wc_10k.copy())
print(f"Tempo do array de pior caso 10k: {time_wc_10k_qs} segundos.")

Tempo do primeiro array de 10k: 0.03214526176452637 segundos.
Tempo do segundo array de 10k: 0.021221399307250977 segundos.
Tempo do terceiro array de 10k: 0.02126789093017578 segundos.
Tempo do array de pior caso 10k: 0.6544842720031738 segundos.


In [118]:
mean_arr_10k_qs = (time_arr1_10k_qs + time_arr2_10k_qs + time_arr3_10k_qs)/3
list_arr_10k_qs = np.array([time_arr1_10k_qs, time_arr2_10k_qs, time_arr3_10k_qs, time_wc_10k_qs, mean_arr_10k_qs])
print(f"Tempo médio de ordenação dos arrays aleatórios de 10k: {mean_arr_10k_qs} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 10k: 0.024878184000651043 segundos.


In [119]:
time_arr1_20k_qs =  tempo_ordenaçao_qs(arr1_20k.copy())
print(f"Tempo do primeiro array de 20k: {time_arr1_20k_qs} segundos.")
time_arr2_20k_qs = tempo_ordenaçao_qs(arr2_20k.copy())
print(f"Tempo do segundo array de 20k: {time_arr2_20k_qs} segundos.")
time_arr3_20k_qs = tempo_ordenaçao_qs(arr3_20k.copy())
print(f"Tempo do terceiro array de 20k: {time_arr3_20k_qs} segundos.")
time_wc_20k_qs = tempo_ordenaçao_qs(arr_wc_20k.copy())
print(f"Tempo do array de pior caso 20k: {time_wc_20k_qs} segundos.")

Tempo do primeiro array de 20k: 0.05776262283325195 segundos.
Tempo do segundo array de 20k: 0.03351569175720215 segundos.
Tempo do terceiro array de 20k: 0.04022502899169922 segundos.
Tempo do array de pior caso 20k: 1.3139960765838623 segundos.


In [120]:
mean_arr_20k_qs = (time_arr1_20k_qs + time_arr2_20k_qs + time_arr3_20k_qs)/3
list_arr_20k_qs = np.array([time_arr1_20k_qs, time_arr2_20k_qs, time_arr3_20k_qs, time_wc_20k_qs, mean_arr_20k_qs])
print(f"Tempo médio de ordenação dos arrays aleatórios de 20k: {mean_arr_20k_qs} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 20k: 0.04383444786071777 segundos.


In [121]:
time_arr1_30k_qs =  tempo_ordenaçao_qs(arr1_30k.copy())
print(f"Tempo do primeiro array de 30k: {time_arr1_30k_qs} segundos.")
time_arr2_30k_qs = tempo_ordenaçao_qs(arr2_30k.copy())
print(f"Tempo do segundo array de 30k: {time_arr2_30k_qs} segundos.")
time_arr3_30k_qs = tempo_ordenaçao_qs(arr3_30k.copy())
print(f"Tempo do terceiro array de 30k: {time_arr3_30k_qs} segundos.")
time_wc_30k_qs = tempo_ordenaçao_qs(arr_wc_30k.copy())
print(f"Tempo do array de pior caso 30k: {time_wc_30k_qs} segundos.")

Tempo do primeiro array de 30k: 0.05420327186584473 segundos.
Tempo do segundo array de 30k: 0.07672595977783203 segundos.
Tempo do terceiro array de 30k: 0.051123619079589844 segundos.
Tempo do array de pior caso 30k: 1.9597694873809814 segundos.


In [122]:
mean_arr_30k_qs = (time_arr1_30k_qs + time_arr2_30k_qs + time_arr3_30k_qs)/3
list_arr_30k_qs = np.array([time_arr1_30k_qs, time_arr2_30k_qs, time_arr3_30k_qs, time_wc_30k_qs, mean_arr_30k_qs])
print(f"Tempo médio de ordenação dos arrays aleatórios de 30k: {mean_arr_30k_qs} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 30k: 0.0606842835744222 segundos.


In [123]:
time_arr1_40k_qs = tempo_ordenaçao_qs(arr1_40k)
print(f"Tempo do primeiro array de 40k: {time_arr1_40k_qs} segundos.")
time_arr2_40k_qs = tempo_ordenaçao_qs(arr2_40k)
print(f"Tempo do segundo array de 40k: {time_arr2_40k_qs} segundos.")
time_arr3_40k_qs = tempo_ordenaçao_qs(arr3_40k)
print(f"Tempo do terceiro array de 40k: {time_arr3_40k_qs} segundos.")
time_wc_40k_qs = tempo_ordenaçao_qs(arr_wc_40k)
print(f"Tempo do array de pior caso de 40k: {time_wc_40k_qs} segundos.")

Tempo do primeiro array de 40k: 0.09372401237487793 segundos.
Tempo do segundo array de 40k: 0.07444643974304199 segundos.
Tempo do terceiro array de 40k: 0.08943653106689453 segundos.
Tempo do array de pior caso de 40k: 2.6382150650024414 segundos.


In [124]:
mean_arr_40k_qs = (time_arr1_40k_qs + time_arr2_40k_qs + time_arr3_40k_qs)/3
list_arr_40k_qs = np.array([time_arr1_40k_qs, time_arr2_40k_qs, time_arr3_40k_qs, time_wc_40k_qs, mean_arr_40k_qs])
print(f"Tempo médio de ordenação dos arrays aleatórios de 40k: {mean_arr_40k_qs} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 40k: 0.08586899439493816 segundos.


In [125]:
time_arr1_50k_qs = tempo_ordenaçao_qs(arr1_50k)
print(f"Tempo do primeiro array de 50k: {time_arr1_50k_qs} segundos.")
time_arr2_50k_qs = tempo_ordenaçao_qs(arr2_50k)
print(f"Tempo do segundo array de 50k: {time_arr2_50k_qs} segundos.")
time_arr3_50k_qs = tempo_ordenaçao_qs(arr3_50k)
print(f"Tempo do terceiro array de 50k: {time_arr3_50k_qs} segundos.")
time_wc_50k_qs = tempo_ordenaçao_qs(arr_wc_50k)
print(f"Tempo do array de pior caso de 50k: {time_wc_50k_qs} segundos.")

Tempo do primeiro array de 50k: 0.09217596054077148 segundos.
Tempo do segundo array de 50k: 0.11461782455444336 segundos.
Tempo do terceiro array de 50k: 0.08540081977844238 segundos.
Tempo do array de pior caso de 50k: 3.3695619106292725 segundos.


In [112]:
mean_arr_50k_qs = (time_arr1_50k_qs + time_arr2_50k_qs + time_arr3_50k_qs)/3
list_arr_50k_qs = np.array([time_arr1_50k_qs, time_arr2_50k_qs, time_arr3_50k_qs, time_wc_50k_qs, mean_arr_50k_qs])
print(f"Tempo médio de ordenação dos arrays aleatórios de 50k: {mean_arr_50k_qs} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 50k: 0.09321506818135579 segundos.


## 2. Fazendo as listas de tempos e médias do método

In [113]:
# Definição das variáveis _qs
list_qs = np.array([list_arr_1k_qs, list_arr_10k_qs, list_arr_20k_qs,
                     list_arr_30k_qs, list_arr_40k_qs, list_arr_50k_qs])

## 3. Salvando os Dados

In [114]:
# Comandos para salvar os arrays _qs
np.save("list_qs", list_qs)

## `Merge Sort`

## 1. Calculando os tempos de ordenação

In [81]:
# Pegando o tempo de ordenação dos 4 arrays
time_arr1_1k_ms =  tempo_ordenaçao_ms(arr1_1k.copy())
print(f"Tempo do primeiro array de 1k: {time_arr1_1k_ms} segundos")
time_arr2_1k_ms = tempo_ordenaçao_ms(arr2_1k.copy())
print(f"Tempo do segundo array de 1k: {time_arr2_1k_ms} segundos")
time_arr3_1k_ms = tempo_ordenaçao_ms(arr3_1k.copy())
print(f"Tempo do terceiro array de 1k: {time_arr3_1k_ms} segundos")
time_wc_1k_ms = tempo_ordenaçao_ms(arr_wc_1k.copy())
print(f"Tempo do array de pior caso de 1k: {time_wc_1k_ms} segundos")

Tempo do primeiro array de 1k: 0.007991313934326172 segundos
Tempo do segundo array de 1k: 0.006997346878051758 segundos
Tempo do terceiro array de 1k: 0.0060079097747802734 segundos
Tempo do array de pior caso de 1k: 0.006002902984619141 segundos


In [82]:
# Fazendo uma média dos 3 casos dos arrays aleatórios (1k)
mean_arr_1k_ms = (time_arr1_1k_ms + time_arr2_1k_ms + time_arr3_1k_ms)/3
list_arr_1k_ms = np.array([time_arr1_1k_ms, time_arr2_1k_ms, time_arr3_1k_ms, time_wc_1k_ms, mean_arr_1k_ms])
print(f"Tempo médio de ordenação dos arrays de 1k: {mean_arr_1k_ms} segundos.")

Tempo médio de ordenação dos arrays de 1k: 0.006998856862386067 segundos.


In [83]:
time_arr1_10k_ms =  tempo_ordenaçao_ms(arr1_10k.copy())
print(f"Tempo do primeiro array de 10k: {time_arr1_10k_ms} segundos.")
time_arr2_10k_ms = tempo_ordenaçao_ms(arr2_10k.copy())
print(f"Tempo do segundo array de 10k: {time_arr2_10k_ms} segundos.")
time_arr3_10k_ms = tempo_ordenaçao_ms(arr3_10k.copy())
print(f"Tempo do terceiro array de 10k: {time_arr3_10k_ms} segundos.")
time_wc_10k_ms = tempo_ordenaçao_ms(arr_wc_10k.copy())
print(f"Tempo do array de pior caso 10k: {time_wc_10k_ms} segundos.")

Tempo do primeiro array de 10k: 0.08957219123840332 segundos.
Tempo do segundo array de 10k: 0.10708212852478027 segundos.
Tempo do terceiro array de 10k: 0.08459043502807617 segundos.
Tempo do array de pior caso 10k: 0.07000041007995605 segundos.


In [84]:
mean_arr_10k_ms = (time_arr1_10k_ms + time_arr2_10k_ms + time_arr3_10k_ms)/3
list_arr_10k_ms = np.array([time_arr1_10k_ms, time_arr2_10k_ms, time_arr3_10k_ms, time_wc_10k_ms, mean_arr_10k_ms])
print(f"Tempo médio de ordenação dos arrays aleatórios de 10k: {mean_arr_10k_ms} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 10k: 0.0937482515970866 segundos.


In [85]:
time_arr1_20k_ms =  tempo_ordenaçao_ms(arr1_20k.copy())
print(f"Tempo do primeiro array de 20k: {time_arr1_20k_ms} segundos.")
time_arr2_20k_ms = tempo_ordenaçao_ms(arr2_20k.copy())
print(f"Tempo do segundo array de 20k: {time_arr2_20k_ms} segundos.")
time_arr3_20k_ms = tempo_ordenaçao_ms(arr3_20k.copy())
print(f"Tempo do terceiro array de 20k: {time_arr3_20k_ms} segundos.")
time_wc_20k_ms = tempo_ordenaçao_ms(arr_wc_20k.copy())
print(f"Tempo do array de pior caso 20k: {time_wc_20k_ms} segundos.")

Tempo do primeiro array de 20k: 0.17310690879821777 segundos.
Tempo do segundo array de 20k: 0.17082715034484863 segundos.
Tempo do terceiro array de 20k: 0.17075300216674805 segundos.
Tempo do array de pior caso 20k: 0.14655065536499023 segundos.


In [86]:
mean_arr_20k_ms = (time_arr1_20k_ms + time_arr2_20k_ms + time_arr3_20k_ms)/3
list_arr_20k_ms = np.array([time_arr1_20k_ms, time_arr2_20k_ms, time_arr3_20k_ms, time_wc_20k_ms, mean_arr_20k_ms])
print(f"Tempo médio de ordenação dos arrays aleatórios de 20k: {mean_arr_20k_ms} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 20k: 0.17156235376993814 segundos.


In [87]:
time_arr1_30k_ms =  tempo_ordenaçao_ms(arr1_30k.copy())
print(f"Tempo do primeiro array de 30k: {time_arr1_30k_ms} segundos.")
time_arr2_30k_ms = tempo_ordenaçao_ms(arr2_30k.copy())
print(f"Tempo do segundo array de 30k: {time_arr2_30k_ms} segundos.")
time_arr3_30k_ms = tempo_ordenaçao_ms(arr3_30k.copy())
print(f"Tempo do terceiro array de 30k: {time_arr3_30k_ms} segundos.")
time_wc_30k_ms = tempo_ordenaçao_ms(arr_wc_30k.copy())
print(f"Tempo do array de pior caso 30k: {time_wc_30k_ms} segundos.")

Tempo do primeiro array de 30k: 0.2656371593475342 segundos.
Tempo do segundo array de 30k: 0.26271653175354004 segundos.
Tempo do terceiro array de 30k: 0.2641146183013916 segundos.
Tempo do array de pior caso 30k: 0.2241840362548828 segundos.


In [88]:
mean_arr_30k_ms = (time_arr1_30k_ms + time_arr2_30k_ms + time_arr3_30k_ms)/3
list_arr_30k_ms = np.array([time_arr1_30k_ms, time_arr2_30k_ms, time_arr3_30k_ms, time_wc_30k_ms, mean_arr_30k_ms])
print(f"Tempo médio de ordenação dos arrays aleatórios de 30k: {mean_arr_30k_ms} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 30k: 0.2641561031341553 segundos.


In [89]:
time_arr1_40k_ms =  tempo_ordenaçao_ms(arr1_40k.copy())
print(f"Tempo do primeiro array de 40k: {time_arr1_40k_ms} segundos.")
time_arr2_40k_ms = tempo_ordenaçao_ms(arr2_40k.copy())
print(f"Tempo do segundo array de 40k: {time_arr2_40k_ms} segundos.")
time_arr3_40k_ms = tempo_ordenaçao_ms(arr3_40k.copy())
print(f"Tempo do terceiro array de 40k: {time_arr3_40k_ms} segundos.")
time_wc_40k_ms = tempo_ordenaçao_ms(arr_wc_40k.copy())
print(f"Tempo do array de pior caso 40k: {time_wc_40k_ms} segundos.")

Tempo do primeiro array de 40k: 0.36394309997558594 segundos.
Tempo do segundo array de 40k: 0.36180639266967773 segundos.
Tempo do terceiro array de 40k: 0.3661832809448242 segundos.
Tempo do array de pior caso 40k: 0.3061556816101074 segundos.


In [90]:
mean_arr_40k_ms = (time_arr1_40k_ms + time_arr2_40k_ms + time_arr3_40k_ms)/3
list_arr_40k_ms = np.array([time_arr1_40k_ms, time_arr2_40k_ms, time_arr3_40k_ms, time_wc_40k_ms, mean_arr_40k_ms])
print(f"Tempo médio de ordenação dos arrays aleatórios de 40k: {mean_arr_40k_ms} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 40k: 0.363977591196696 segundos.


In [91]:
time_arr1_50k_ms =  tempo_ordenaçao_ms(arr1_50k.copy())
print(f"Tempo do primeiro array de 50k: {time_arr1_50k_ms} segundos.")
time_arr2_50k_ms = tempo_ordenaçao_ms(arr2_50k.copy())
print(f"Tempo do segundo array de 50k: {time_arr2_50k_ms} segundos.")
time_arr3_50k_ms = tempo_ordenaçao_ms(arr3_50k.copy())
print(f"Tempo do terceiro array de 50k: {time_arr3_50k_ms} segundos.")
time_wc_50k_ms = tempo_ordenaçao_ms(arr_wc_50k.copy())
print(f"Tempo do array de pior caso de 50k: {time_wc_50k_ms} segundos.")

Tempo do primeiro array de 50k: 0.45903968811035156 segundos.
Tempo do segundo array de 50k: 0.46154356002807617 segundos.
Tempo do terceiro array de 50k: 0.4570910930633545 segundos.
Tempo do array de pior caso de 50k: 0.39849853515625 segundos.


In [92]:
mean_arr_50k_ms = (time_arr1_50k_ms + time_arr2_50k_ms + time_arr3_50k_ms)/3
list_arr_50k_ms = np.array([time_arr1_50k_ms, time_arr2_50k_ms, time_arr3_50k_ms, time_wc_50k_ms, mean_arr_50k_ms])
print(f"Tempo médio de ordenação dos arrays aleatórios de 50k: {mean_arr_50k_ms} segundos.")

Tempo médio de ordenação dos arrays aleatórios de 50k: 0.45922478040059406 segundos.


## 2. Fazendo as listas de tempos e médias do método

In [93]:
# Definição das variáveis _ms
list_ms = np.array([list_arr_1k_ms, list_arr_10k_ms, list_arr_20k_ms,
                    list_arr_30k_ms, list_arr_40k_ms, list_arr_50k_ms])

## 3. Salvando os Dados

In [94]:
# Comandos para salvar os arrays _ms
np.save("list_ms", list_ms)

### Estrutura de Índices para `list_arr_(n)k`

1. `list_arr_(n)k`, onde `(n)k` representa o tamanho do array (ex: 10k, 50k, 100k):

* **Índices `[0]` a `[2]`: Tempos de Execução (Arrays Aleatórios)**
    * **`[0]`:** Tempo da 1ª execução aleatória.
    * **`[1]`:** Tempo da 2ª execução aleatória.
    * **`[2]`:** Tempo da 3ª execução aleatória.

* **Índice `[3]`: Tempo de Execução (Pior Caso)**
    * Representa o tempo de execução para o array ordenado no pior caso (geralmente decrescente para algoritmos de ordenação).

* **Índice `[4]`: Média dos Tempos Aleatórios**
    * Valor médio calculado a partir dos tempos nos índices `[0]`, `[1]`, e `[2]`.

    
2. `list_x`, onde x é a abreviação do método de ordenamento:
* **Índices `[0]` a `[5]`**: Representam as listas geradas pelos tempos relacionados a cada tamanho de array em progressão
(1k, 10k, 20k, 30k, 40k, 50k).

